import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">FrameTwo</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/page29">Page29</Link>
        </li>
        <li>
          <Link to="/page30">Page30</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/page28">Page28</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/page27">Page27</Link>
        </li>
        <li>
          <Link to="/page26">Page26</Link>
        </li>
        <li>
          <Link to="/page25">Page25</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/page7">Page7</Link>
        </li>
        <li>
          <Link to="/page8">Page8</Link>
        </li>
        <li>
          <Link to="/page9">Page9</Link>
        </li>
        <li>
          <Link to="/page10">Page10</Link>
        </li>
        <li>
          <Link to="/page11">Page11</Link>
        </li>
        <li>
          <Link to="/page12">Page12</Link>
        </li>
        <li>
          <Link to="/page13">Page13</Link>
        </li>
        <li>
          <Link to="/page14">Page14</Link>
        </li>
        <li>
          <Link to="/page15">Page15</Link>
        </li>
        <li>
          <Link to="/page24">Page24</Link>
        </li>
        <li>
          <Link to="/page16">Page16</Link>
        </li>
        <li>
          <Link to="/page17">Page17</Link>
        </li>
        <li>
          <Link to="/page18">Page18</Link>
        </li>
        <li>
          <Link to="/page19">Page19</Link>
        </li>
        <li>
          <Link to="/page20">Page20</Link>
        </li>
        <li>
          <Link to="/page21">Page21</Link>
        </li>
        <li>
          <Link to="/page22">Page22</Link>
        </li>
        <li>
          <Link to="/page31">Page31</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
